EmailDeveloperUtilities/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from . import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'EmailDeveloperUtilities.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^QCTool/', include('QCTool.urls', namespace="QCTool")),
    url(r'^$', views.index, name="home"),
)

QCTool/urls.py
__author__ = 'ychai'

from django.conf.urls import patterns, url

from QCTool import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^result/$', views.result, name='result'),
    url(r'^litmusHelper/$', views.litmusHelper, name='litmusHelper')
    # url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    # url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    # url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

QCTool/models.py
#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

from django.db import models
from HTMLParser import HTMLParser
from urlparse import urlparse
from htmlentitydefs import entitydefs
import re, codecs


class QCError(models.Model):
    line = models.IntegerField(max_length=10000)
    offset = models.IntegerField(max_length=10000)
    error_message = models.CharField(max_length=50)
    attribute = models.CharField(max_length=20)
    error_code = models.CharField(max_length=500)
    campaign_name = models.CharField(max_length=20)
    campaign_id = models.CharField(max_length=10)
    version = models.IntegerField(max_length=100)


class QCHTMLParser(HTMLParser):
    def __init__(self, data):
        HTMLParser.__init__(self)
        self.originalSource = data
        self.source = data
        self.errMsg = {
            #dictionary for errors. Output method will use the "key" to get the "value" to output the error.
            "invalidImage": "The dimension of the image is invalided.",
            "replaceLink": "Word \"replace\" found in link.",
            "tbd": "Word \"tbd\" found in link.",
            "spaceLink": "Space found before http.",
            "noDotCom": "Can't find .com in the url host.",
            "doubleHttp": "Found http twice in the url.",
            "wrongUrlQuery": "? and & symbol found with wrong order in URL.",
            "wrongFragment": "& or ? symbol found after # symbol, please make sure it's correct.",
            "emptyValue": "Empty value found in ",
            "noAttr": "Unable to find attribute ",
            "returnInAlias": "Found return symbol in alias.",
            "specialChar": "Found special character in the copy.",
            "noHttp": "No http found at the beginning of the url.",
            "wrongConv": "Conversion detected but value invalided.",
            "wrongEntity": "Wrong escaped character found",
            "duplicatedAlias": "Found alias duplicated with former alias",
            "wrongScheme": "Wrong scheme found in the link.",
        }
        #filter is used for some ET links
        self.filter = [
            "%%view_email_url%%",
            "%%ftaf_url%%",
            "%%=GetSocialPublishURL(",
            "%%unsub_center_url%%",
            "%%profile_center_url%%",
            "%%=redirectto("
        ]
        #alias dict is used for counting alias, Key=AliasName Value=Times
        self.aliasDict = {}
        #alias List is used for alias & rawlink pairs
        self.aliasList = []
        #each error will be append to this list
        self.errors = []
        #dict used for counting, notice "plain_link" refers to the aTag which has href
        self.aCount = {
            "view_email": 0,
            "plain_link": 0,
            "empty_link": 0,
            "alias": 0,
            "empty_alias": 0,
            "mail": 0,
            "tel": 0,
            "conversion": 0,
        }
        self.amp = ""
        #cache current line
        self.cur_line = ""
        #signal used for catching title data,
        #I'm still looking into this issue, because if title is null, handle data won't be called
        self.signals = {
            "title": 0, # 0=Unreached, 1=Reached, 2=DataFound
        }
        #below is the special characters used for matching
        mdash = unicode("—", encoding="utf-8")
        lquo = unicode("‘", encoding="utf-8")
        ldquo = unicode("“", encoding="utf-8")
        ellipsis = unicode("…", encoding="utf-8")
        #the characters will be put in to below list
        self.specialCharList = [mdash, lquo, ldquo, ellipsis]

    def run(self):
        self.get_amp()
        code = self.source.split('\n')
        for c in code:
            self.cur_line = c
            for s in c:
                self.feed(s)
            self.feed('\n')

    #decode_html function is used for correct decode our html file
    #if the input is already unicode string, we don't have to use beautiful soup to decode the html
    #If we can easily decode the code to "utf-8", we don't need to use Beautiful Soup also.

    #change the signal
    def changeSignal(self, target, number):
        self.signals[target] = number

    #input error to the list, param "name" used to indicate the specific wrong attr
    def errInput(self, position, errMsg, name=None):
        if errMsg != "over500":
            code = self.cur_line
        else:
            code = "see comments"
        self.errors.append([position[0], position[1], errMsg, name, code])

    #if image don't have either width or height, or both are 0 then it will be reported
    #this may need further discussion, but now it is still working
    def invalidImage(self, width, height):
        if width and height:
            if width == "0" and height == "0":
                self.errInput(self.getpos(), "invalidImage")
        else:
            self.errInput(self.getpos(), "invalidImage")

    #if alias is not found in dict's key, then create one otherwise add 1
    def isAliasDuplicated(self, alias):
        bObj = False
        for item in alias:
            lower_item = item.lower()
            if self.aliasDict.has_key(lower_item):
                self.aliasDict[lower_item] += 1
                bObj = True
            else:
                self.aliasDict[lower_item] = 1
        return bObj

    #the logic is a little confused but it use "urlparse", so check the document
    def urlValidation(self, url):
        if any(url.lower().startswith(x.lower()) for x in self.filter):
            return
        if "replace" in url.lower():
            self.errInput(self.getpos(), "replaceLink")
        elif "TBD" in url.upper():
            self.errInput(self.getpos(), "tbd")
        else:
            purl = urlparse(url)
            if purl.scheme == "" and purl.netloc == "":
                if "http" in purl.path.lower():
                    self.errInput(self.getpos(), "spaceLink")
                elif "tel" in purl.path:
                    pass
                    # UrlMsg += " Tel link;"
                else:
                    self.errInput(self.getpos(), "noHttp")
            elif purl.scheme.lower() == "tel":
                pass
                # UrlMsg += " Tel link;"
            elif purl.scheme.lower() == "mailto":
                pass
                # UrlMsg += " Mail link;"
            elif "http" in purl.scheme.lower():
                if "http" in purl.netloc.lower():
                    self.errInput(self.getpos(), "doubleHttp")
            else:
                self.errInput(self.getpos(), "wrongScheme")

            if purl.query =="":
                if "&" in purl.netloc or "&" in purl.path:
                    self.errInput(self.getpos(), "wrongUrlQuery")
            elif purl.query != "" and ( "&" in purl.path or "?" in purl.query):
                self.errInput(self.getpos(), "wrongUrlQuery")
            if purl.fragment != "" and ( "&" in purl.fragment or "?" in purl.fragment):
                self.errInput(self.getpos(), "wrongFragment")

    #using urlparse to get the scheme of a url
    def getUrlScheme(self, url):
        o = urlparse(url)
        if o.path.startswith("tel:"):
            return "tel"
        return o.scheme

    #check if alias contain return
    def hasReturn(self, alias):
        for item in alias:
            if "\n" in item:
                self.errInput(self.getpos(), "returnInAlias")

    #check if has special char
    def hasSpecialChar(self, content):
        regex = re.compile(r'^[^\x20-\x7E\n\s\r]+$', re.IGNORECASE)
        match = regex.search(content)
        if match:
            self.errInput(self.getpos(), "specialChar")
        else:
            return
        # if any(x in content for x in self.specialCharList):
        #     self.errInput(self.getpos(), "specialChar")

    #only equal true then it will pass the validation
    def convValidation(self, value):
        if value.lower() == "true":
            return True
        return False

    #login the data to alias list
    def aliasInput(self, alias, rawlink, conversion):
        isDuplicated = self.isAliasDuplicated(alias)
        if conversion or conversion == "":
            hasConversion = self.convValidation(conversion)
            if not hasConversion:
                hasConversion = "invalid"
                self.errInput(self.getpos(), "wrongConv")
        else: hasConversion = False
        if not alias:
            aliasStr = "None/Empty"
        else:
            aliasStr = "|".join(alias)
        if not rawlink:
            rawlink = "None/Empty"
        hasConversion = str(hasConversion)
        isDuplicated = str(isDuplicated)
        self.aliasList.append([aliasStr, rawlink, hasConversion, isDuplicated])

    #count the number of the link
    #if we can't get an attr, we will get None
    def count(self, alias, link, conversion):
        scheme = "no href"
        if link is None:
            self.errInput(self.getpos(), "noAttr", "href")
        else:
            scheme = self.getUrlScheme(link)
            self.aCount["plain_link"] += 1
            if link:
                if scheme == "tel":
                    self.aCount["tel"] += 1
                elif scheme == "mailto":
                    self.aCount["mail"] += 1
                elif link == "%%view_email_url%%":
                    self.aCount["view_email"] += 1
            else:
                self.errInput(self.getpos(), "emptyValue", "href")
                self.aCount["empty_link"] += 1
        if len(alias) == 0 and scheme != "tel" and scheme != "mailto":
            self.errInput(self.getpos(), "noAttr", "alias")
        elif len(alias) > 0 and scheme != "tel" and scheme != "mailto":
            self.aCount["alias"] += 1
        elif any(x == "" for x in alias):
            self.aCount["empty_alias"] += 1
            self.errInput(self.getpos(), "emptyValue", "alias")
        if conversion or conversion == "":
            self.aCount["conversion"] += 1

QCTool/views.py
#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

from django.shortcuts import render, get_object_or_404
from QCTool.models import QCHTMLParser
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone


def index(request):
    return render(request, 'QCTool/index.html')


def result(request):
    source = request.POST['source']
    bot = QCHTMLParser(source)
    bot.run()
    result_obj = bot.getResult()
    return render(request, 'QCTool/result.html', result_obj)

def litmusHelper(request):
    return render(request, 'QCTool/litmusHelper.html')

QCTool/templates/QCTool/index.html
<!DOCTYPE html>
<html>
<head>
    <title>QCTool</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/foundation.min.css' %}" />
</head>
<body>
    <div class="row"><h4 class="large-8 column"><a href="./litmusHelper">Litmus Helper is here, click me!</a></h4></div>
    <div class="row"><h2 class="large-8 column">Input your code here</h2></div>
    <div class="row">
        <div class="large-8 column">
            <form action="{% url 'QCTool:result' %}" method="post">
                {% csrf_token %}
                <p><textarea name="source" id="source" cols="100" rows="30"></textarea></p>
                <input class="button" type="submit" value="Submit"/>
            </form>
        </div>
    </div>
</body>
</html>

QCTool/templates/QCTool/litmusHelper.html
<!DOCTYPE html>
<html>
<head>
    <title>Litmus Helper</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
    <script src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
    <script src="{% static 'js/angular.min.js' %}"></script>
    <script src="{% static 'js/litmusHelper.js' %}"></script>
</head>
<body>
    <div class="container" ng-app="Linker">
        <div class="row"><div class="col-lg-8"><h2>Input the link of your render test&nbsp;&nbsp;<small>(Not the published one)</small></h2></div></div>
        <div class="row">
            <div class="col-lg-12">
                <form role="form" class="form-horizontal">
                    <div class="form-group" ng-controller="linkInput">
                        <label for="Link" class="col-lg-1">Link here:</label>

                        <div class="col-lg-11">
                            <input type="text" class="form-control" id="inputLink" placeholder="Enter link" ng-model="data.litmusURL" ng-change="change()">
                            <p class="bg-danger {$data.warningDisplay$}" style="margin-top: 10px; padding: 5px 10px;">Invalid link. Please input your link.</p></div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <dl class="dl-horizontal {$data.listDisplay$}" ng-controller="renderLink">
                    <div ng-repeat="device in config">
                        <dt>{$device.name$}</dt><dd><a href='{$renderLink(device)$}'>{$renderLink(device)$}</a></dd>
                    </div>
                </dl>
            </div>
        </div>
    </div>
</body>
</html>

QCTool/templates/QCTool/result.html
<!DOCTYPE html>
<html>
<head>
    <title>Campaign Result {% if cid %}for {{ cid }}{% endif %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/foundation.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script>
        $(function(){
            $('.toggle').click(function(){
                $(this).parents().siblings('.toggTarget').toggle();
                return false;
            });
        });
    </script>
</head>
<body>
<a id="openonly" href="#" target="_blank"></a>
    {% if amp %}
    <div class="row panel">
        <h4>AMP Script: <a href="#" class="toggle">Expand/Hide</a></h4>
        <div class="large-10 columns toggTarget word-break">
            {% autoescape off %}
            {{ amp }}
            {% endautoescape %}
        </div>
    </div>
    <hr/>
    {% endif %}
    <div class="row panel">
        <h4>Errors:</h4>
        {% if errorList %}
            <table>
            {% load dict_extras %}
            {% load merge_string %}
            {% for error in errorList %}
                <tr>
                    <td width="50">HTML</td>
                    <td width="1"></td>
                    <td width="150">Line: {{ error.0 }}{% if error.2 != "over500" %},Offset: {{ error.1 }}{% endif %}</td>
                    <td width="500" class="word-break">
                        {% if error.4 == "see comments" %}{{ error.4 }}{% else %}{% with a=":"|merge_str:error.1 %}{{ error.4|slice:a }}{% endwith %}{% with b=error.1 %}<span style="background-color: #ffff00; color: #cf2a0e;">{{ error.4|key:b }}</span>{% endwith %}{% with num=error.1|add:1 %}{% with c=num|merge_str:":" %}{{ error.4|slice:c }}{% endwith %}{% endwith %}
                        {% endif %}
                    </td>
                    <td width="1"></td>
                    <td width="200">{{ errMsg|key:error.2 }}{% if error.3 %}{{ error.3 }}{% endif %}</td>
                </tr>
            {% endfor %}
            </table>
        {% endif %}
    </div>
    <hr/>
    <div class="row panel">
        <h4>Link Count:</h4>
        {% if aCount %}
            <table>
                <tr>
                    <td width="200">Plain Link (Alias + Mail + Tel)</td>
                    {%  with total=aCount.alias|add:aCount.mail|add:aCount.tel %}
                    <td width="200" {% if aCount.plain_link == total %}style="background-color: #43ac6a; color: #ffffff;"{% else %}style="background-color: #f04124; color: #ffffff;" {% endif %}>{{ aCount.plain_link }}</td>
                    {% endwith %}
                </tr>
                <tr>
                    <td width="200">Alias</td>
                    <td width="200">{{ aCount.alias }}</td>
                </tr>
                <tr>
                    <td width="200">Mail Link</td>
                    <td width="200">{{ aCount.mail }}</td>
                </tr>
                <tr>
                    <td width="200">Tel Link</td>
                    <td width="200">{{ aCount.tel }}</td>
                </tr>
                <tr>
                    <td width="200">Conversion</td>
                    <td width="200">{{ aCount.conversion }}</td>
                </tr>
                <tr>
                    <td width="200">View Email Link</td>
                    <td width="200">{{ aCount.view_email }}</td>
                </tr>
                <tr>
                    <td width="200">Empty Link</td>
                    <td width="200" {% if aCount.empty_link > 1 %}style="background-color: #f04124; color: #ffffff;" {% endif %}>{{ aCount.empty_link }}</td>
                </tr>
                <tr>
                    <td width="200">Empty Alias</td>
                    <td width="200" {% if aCount.empty_alias > 1 %}style="background-color: #f04124; color: #ffffff;" {% endif %}>{{ aCount.empty_alias }}</td>
                </tr>
            </table>
        {% endif %}
    </div>
    <div class="row panel">
        <h4>Alias Dict:</h4>
        {% if aliasDict %}
            <table>
                <tr>
                    <th class="text-left" width="200">Alias Name</th>
                    <th class="text-left" width="200">Duplicated Times</th>
                </tr>
            {% for alias, times in aliasDict.items %}
                <tr>
                    <td>{{ alias }}</td>
                    <td {% if times > 1 %}style="background-color: #f04124; color: #ffffff;" {% endif %}>{{ times }}</td>
                </tr>
            {% endfor %}
            </table>
        {% endif %}
    </div>
    <div class="row panel">
        <h4>Alias Mapping:</h4>
        {% if aliasList %}
            <table>
                <tr>
                    <th class="text-left" width="200">Alias Name</th>
                    <th class="text-left" width="400">Raw Link</th>
                    <th class="text-left" width="150">Conversion</th>
                    <th class="text-left" width="150">is Duplicated?</th>
                </tr>
            {% for aliasObj in aliasList %}
                <tr>
                    <td {% if aliasObj.0 == "None/Empty" %}style="background-color: #f04124; color: #ffffff;" {% endif %}>{{ aliasObj.0 }}</td>
                    <td><a href="{{ aliasObj.1 }}" target="_blank">{{ aliasObj.1 }}</a></td>
                    <td {% if aliasObj.2 == "True" %}style="background-color: #74bfdd; color: #000000;" {% elif aliasObj.2 == "False" %}style="background-color: #f08a24; color: #000000;" {% endif %}>{{ aliasObj.2 }}</td>
                    <td {% if aliasObj.3 == "True" %}style="background-color: #f04124; color: #ffffff;" {% endif %}>{{ aliasObj.3 }}</td>
                </tr>
            {% endfor %}
            </table>
        {% endif %}
    </div>
</body>
</html>